# Generated by Django 3.0.5 on 2022-03-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('pemail', models.CharField(max_length=50)),
                ('paddress', models.CharField(max_length=300)),
                ('pphone', models.CharField(max_length=50)),
                ('pimage', models.ImageField(upload_to='crud/images')),
            ],
        ),
    ]
