# Generated by Django 3.0.5 on 2022-03-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudd', '0002_patientdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='pimage',
        ),
    ]
