# Generated by Django 3.0.5 on 2022-03-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudd', '0003_remove_patientdetails_pimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeedetails',
            options={'verbose_name': 'EmployeeDetails'},
        ),
        migrations.AlterModelOptions(
            name='patientdetails',
            options={'verbose_name': 'PatientDetails'},
        ),
    ]
