# Generated by Django 3.0.5 on 2022-03-29 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudd', '0006_auto_20220327_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdetails',
            options={},
        ),
    ]
