# Generated by Django 3.0.5 on 2022-03-29 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudd', '0007_auto_20220329_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdetails',
            options={'verbose_name_plural': 'Patient Details'},
        ),
    ]
