# Generated by Django 3.0.5 on 2022-03-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudd', '0011_medicinedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinedetails',
            name='mprice',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
