# Generated by Django 3.0.5 on 2022-03-30 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudd', '0012_medicinedetails_mprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinedetails',
            name='mtype',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
