# Generated by Django 3.0.5 on 2022-03-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudd', '0013_medicinedetails_mtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarydetails',
            name='samount',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
