# Generated by Django 3.0.5 on 2022-03-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudd', '0014_salarydetails_samount'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPDDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oname', models.CharField(max_length=50)),
                ('oaddress', models.CharField(max_length=50, null=True)),
                ('ophone', models.CharField(max_length=16, null=True)),
            ],
            options={
                'verbose_name_plural': 'OPD Details',
            },
        ),
    ]
