# Generated by Django 3.0.5 on 2022-03-30 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudd', '0015_opddetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='opddetails',
            name='odate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
