# Generated by Django 3.0.5 on 2022-04-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudd', '0018_auto_20220330_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opname', models.CharField(max_length=50)),
                ('odname', models.CharField(max_length=50)),
                ('opdate', models.CharField(max_length=50)),
                ('opcause', models.CharField(max_length=50)),
                ('oproom', models.CharField(max_length=300)),
                ('opphone', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'OT Details',
            },
        ),
    ]
