# Generated by Django 3.0.5 on 2022-04-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudd', '0019_otdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='BEDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broom', models.CharField(max_length=50)),
                ('bfloor', models.CharField(max_length=50)),
                ('bseat', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'BED Details',
            },
        ),
    ]
